### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [m333il/INM_prac#1]
1) В Фортране лучше использовать двумерную индексацию для матриц.
2) Нет таблиц с результатами тестов.
3) Не хватает реализации с BLAS на Фортране.
4) Нет LAPACK.

**Comment by m333il** [comment]
В программе на LAPACK нужно выполнять проверку результатов? Или достаточно запустить нужную функцию и измерить время?

**Comment by dzheltkov** [comment]
Можно без проверки.

**Comment by m333il** [comment]
Сделано
