### ISSUE TITLE
Замечания по методу Арнольди

### ISSUE THREAD

**Issue by dzheltkov** [m333il/INM_prac#2]
1. От матрицы требуются только размеры и матвек, поэтому она должна передаваться в функцию, осуществляющую метод Арнольди, или как размер и функция (лучше использовать `std::functional`, тогда возможно передать и класс с реализованным `operator()` ), или как шаблон, в котом реализованы операции `matvec` и, например, `order`.
2. Нет поиска собственных значения для полученной Хессенберговой матрицы.

**Comment by dzheltkov** [comment]
0. Смотрите замечение 1 в предыдущем списке.
1. Делать `num_threads` глобальной переменной -- не лучшая идея.
2. Не хватает MPI версии.

**Comment by m333il** [comment]
Все исправил, загрузил MPI версию

**Comment by m333il** [comment]
Загрузил отчет

**Comment by dzheltkov** [comment]
В целом задания зачтены, но в MPI версии используется шаблонный тип, а работать при этом корректно будет только для `double`.

**Comment by m333il** [comment]
Да, просто при пересылке сообщений надо указывать прямо какой тип пересылается (в данном случае MPI_DOUBLE), поэтому сделал так.
